spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasks-db
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: false
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration
