spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak:8080/realms/tasks/protocol/openid-connect/certs
          issuer-uri: http://keycloak:8080/realms/tasks